package:
  name: pyXSteam
  version: "0.13.1"

source:
  git_rev: v0.4.0
  git_url: https://github.com/wgurecky/pyXSteam.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pyXSteam

about:
  home: https://github.com/wgurecky/pyXSteam
  license: LGPL2
