package:
  name: pyxsteam
  version: "0.4.0"

source:
  git_rev: v0.4.0
  git_url: https://github.com/wgurecky/pyXSteam.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pyXSteam

about:
  home: https://github.com/drunsinn/pyXSteam
  license: LGPL2
